[book]
authors = ["zimkov"]
language = "ru"
src = "src"
title = "Система автономного позиционирования и управления БПЛА без GPS"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []
