[book]
authors = ["Jho00"]
language = "ru"
src = "src"
title = "system-engineering-playbook"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"
# Добавляем обязательные параметры конфигурации
enabled = true
renderers = ["html"]  # Указываем, для каких рендереров работает preprocessor

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []