openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: API documentation for the application
servers:
  - url: /api
    description: API prefix

paths:
  /ping:
    get:
      tags:
        - Health Check
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ok"

components:
  schemas:
    Ok:
      type: object
      properties:
        ok:
          type: boolean
          example: true
      required:
        - ok
